# Generated by Django 6.0.6 on 2026-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(default="Behind the Screen", max_length=100),
                ),
                ("paragraph_1", models.TextField()),
                ("paragraph_2", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Iduwara Nisal", max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Aspiring AI Engineer & Machine Learning Enthusiast 🚀",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    models.CharField(
                        help_text="e.g., Matara, Sri Lanka", max_length=100
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="e.g., Information Systems", max_length=100
                    ),
                ),
                (
                    "interest",
                    models.CharField(help_text="e.g., Deep Learning", max_length=100),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Machine Learning", max_length=100
                    ),
                ),
                ("description", models.TextField()),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma separated, e.g., Python, Flask, Pandas",
                        max_length=255,
                    ),
                ),
                ("project_link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("order", models.IntegerField(default=0, help_text="To sort projects")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
