# Generated by Django 6.0.6 on 2026-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_aboutsection_herosection_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosection",
            name="github_link",
            field=models.URLField(
                blank=True, help_text="e.g., https://github.com/iduwaranisal", null=True
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="linkedin_link",
            field=models.URLField(
                blank=True,
                help_text="e.g., https://linkedin.com/in/iduwaranisal",
                null=True,
            ),
        ),
    ]
